name: bloc_testing
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  lint: ^1.10.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
